version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/examples/01-crud-with-auth"
    schedule:
      interval: "weekly"
